services:
  app:
    build:
      context: .
    ports:
      - "8008:8000"
    volumes:
      - .:/app
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "chat_app.asgi:application"]
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5555:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]
